-- creating a new database
create database retail_analytics_db;

use retail_analytics_db;

show tables;

select * from customer_profiles;
select * from product_inventory;
select * from sales_transaction;

-- finding duplicate transactions
select
transactionid, count(*) as occurence
from sales_transaction
group by transactionid
having occurence > 1;

-- craeting new table with unique transactions
create table sales_transaction_copy as
select
distinct *
from sales_transaction;

-- remove original sales_transaction
drop table if exists sales_transaction;

rename table sales_transaction_copy to sales_transaction;

-- identify the discrepancies in the price
select
t.transactionid,
t.price as transaction_price,
p.price as product_price
from sales_transaction as t
join product_inventory as p
on t.productid = p.productid
where t.price <> p.price;

SET SQL_SAFE_UPDATES = 0;

-- update the discrepancies
update sales_transaction as t
join product_inventory as p
on t.productid = p.productid
set t.price = p.price
where t.price <> p.price;

SET SQL_SAFE_UPDATES = 1;

-- identify empty values
select
count(*)
from customer_profiles
where customerid = ''
or age = ''
or gender = ''
or location = ''
or joindate = '';

-- replace empty value with nulls
update customer_profiles
set location = null
where location = '';

-- identify null values in customer data
select
count(*)
from customer_profiles
where customerid is null
or age is null
or gender is null
or location is null
or joindate is null;

-- replace null with unknown in customer data
update customer_profiles
set age = ifnull(age, 'Unknown'),
customerid = ifnull(customerid, 'Unknown'),
gender = ifnull(gender, 'Unknown'),
location = ifnull(location, 'Unknown'),
joindate = ifnull(joindate, 'Unknown');

-- changing transactiondate from text to date
create table sales_transaction_updated as
select
*,
str_to_date(transactiondate, '%d-%m-%Y') as TransactionDate_updated
from sales_transaction;

drop table if exists sales_transaction;

rename table sales_transaction_updated to sales_transaction;

alter table sales_transaction
drop column transactiondate;

alter table sales_transaction
rename column TransactionDate_updated to TransactionDate;

-- finding total sales and quantity sold
select
productid as ProductID,
sum(quantitypurchased) as TotalUnitsSold,
round(sum(quantitypurchased * price), 2) as TotalSales
from sales_transaction
group by productid
order by TotalSales desc;

-- transactions per customer
select
CustomerID, count(transactionid) as NumberOfTransactions
from sales_transaction
group by CustomerID
order by NumberOfTransactions desc;

-- performance of product category
select
p.Category,
sum(s.quantitypurchased) as TotalUnitsSold,
round(sum(s.quantitypurchased * s.price), 2) as TotalSales
from sales_transaction as s
join product_inventory as p
on s.productid = p.productid
group by p.Category
order by TotalSales desc;

-- top 10 products with highest sales
select
ProductID,
round(sum(quantitypurchased * price), 2) as TotalRevenue
from sales_transaction
group by ProductID
order by TotalRevenue desc
limit 10;

-- making view of top 10 products with highest sales
create or replace view top_products as
select
ProductID,
round(sum(quantitypurchased * price), 2) as TotalRevenue
from sales_transaction
group by ProductID
order by TotalRevenue desc
limit 10;

-- total revenue
select
round(sum(price * quantitypurchased), 2) as TotalRevenue
from sales_transaction;

-- total revenue generated by top 10 products with highest sales
select
round(sum(totalrevenue), 2) as TotalRevenueByTopProducts
from top_products;

-- 10 products with least amount of units sold
select
ProductID,
sum(quantitypurchased) as TotalUnitsSold
from sales_transaction
group by ProductID
having TotalUnitsSold > 1
order by TotalUnitsSold asc
limit 10;

-- finding sales trends
select
TransactionDate,
count(transactionid) as Transaction_count,
round(sum(quantitypurchased), 2) as TotalUnitsSold,
round(sum(quantitypurchased * price), 2) as TotalSales
from sales_transaction
group by TransactionDate
order by TransactionDate asc;

-- monthwise growth rate
with sales_total as (
    select
    month(transactiondate) as month,
    round(sum(quantitypurchased * price), 2) as total_sales
    from sales_transaction
    group by month
    order by month asc
)
select
*,
lag(total_sales) over(order by month) as previous_month_sales,
round(((total_sales - lag(total_sales) over(order by month)) / lag(total_sales) over(order by month)) * 100, 2)
as mom_growth_percentage
from sales_total;

-- number of transaction along with the total amount spent by each customer
select
CustomerID,
count(transactionid) as NumberOfTransactions,
round(sum(quantitypurchased * price), 2) as TotalSpent
from sales_transaction
group by CustomerID
having NumberOfTransactions > 10 and TotalSpent > 1000
order by TotalSpent desc;

-- low purchase frequency in the company
select
CustomerID,
count(transactionid) as NumberOfTransactions,
sum(quantitypurchased * price) as TotalSpent
from sales_transaction
group by CustomerID
having NumberOfTransactions <= 2
order by NumberOfTransactions asc,
TotalSpent desc;

-- repeat purchase
select
CustomerID,
ProductID,
count(ProductID) as TimesPurchased
from sales_transaction
group by CustomerID,
ProductID
having TimesPurchased > 1
order by TimesPurchased desc;

-- duration between the first and the last purchase of the customer -> Loyality Indicators
SELECT
CustomerID,
MIN(cast(transactiondate as date)) AS FirstPurchase,
MAX(cast(transactiondate as date)) AS LastPurchase,
DATEDIFF(MAX(cast(transactiondate as date)), MIN(cast(transactiondate as date))) AS DaysBetweenPurchases
FROM sales_transaction
GROUP BY CustomerID
HAVING DaysBetweenPurchases > 0
ORDER BY DaysBetweenPurchases DESC;

-- Customer Segmentation
with segment as(
    select
    c.customerid,
    case
        when sum(quantitypurchased) between 1 and 10 then 'Low'
        when sum(quantitypurchased) between 11 and 30 then 'Med'
        else 'High'
    end as CustomerSegment
    from customer_profiles as c
    join sales_transaction as s
    on c.customerid = s.customerid
    group by c.customerid
)
select
CustomerSegment,
count(*)
from segment
group by CustomerSegment;

-- total revenue
select
sum(price * quantitypurchased) as TotalRevenue
from sales_transaction;

-- top 10 customers with highest spending
select
customerid,
round(sum(price * quantitypurchased), 2) as TotalSpending
from sales_transaction
group by customerid
order by TotalSpending desc
limit 10;